spring.application.name=complaint-service

# Server port
server.port=8080

# Neon PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-lingering-cake-a1pa3ebw-pooler.ap-southeast-1.aws.neon.tech/complaint_service?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sIC4PlkDv8XL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Kafka Admin / Topic
spring.kafka.admin.fail-fast=false
app.kafka.topics.complaint-created=${COMPLAINT_CREATED_TOPIC:complaint-topic}
